### ISSUE TITLE
Modify `find` Command to Accept Prefixes

### ISSUE THREAD

**Issue by RobotWizzard** [AY2425S1-CS2103T-T15-1/tp#175]
Modify the `find` command to accept prefixes `n/`, `p`, `e/`, `t/`, just like the `cadd` command. The `find` command finds clients whose details match one or more of the prefixes. Found clients are displayed based on the number of prefixes matched.

The `k/` prefix matches in all fields, and can accept duplicates. Duplicate `k/` arguments match separately (i.e. `k/bernice k/yu` will match "bernice" and "yu", whereas `k/bernice yu` will match "bernice yu").

---

For example, if the app currently stores clients
1. `John Doe; Phone: 98765432; Email: johnd@example.com; Tags: [owesMoney][friends]`
2. `John Tan; Phone: 00800912; Email: johnt@example.com; Tags: [colleagues][friends]`
3. `Bernice Yu; Phone: 12345789; Email: berniceyu@example.com; Tags: [colleagues][friends]`

<br>

the command `find n/John p/00800912` will result in:
1. <code><b>John</b> Doe; Phone: 98765432; Email: johnd@example.com; Tags: [owesMoney][friends]</code>
2. <code><b>John</b> Tan; Phone: <b>00800912</b>; Email: johnt@example.com; Tags: [colleagues][friends]</code>

---

- [x] Update command parser
- [x] Update command
- [x] Update UG
- [x] Add tests

**Comment by winstonlimjy** [comment]
Perhaps could modify "find" command, if it is to filter the list by tags
