### ISSUE TITLE
Customer list in rental information panel renders incorrectly

### ISSUE THREAD

**Issue by zackjh** [AY2425S1-CS2103T-T15-1/tp#230]
<img width="223" alt="Screenshot 2024-11-04 at 2 27 46 PM 1" src="https://github.com/user-attachments/assets/09bef790-69e0-417c-9052-fe1a031eff44">

There should not be any nested square brackets.

**Comment by gohsl99** [comment]
Issue fixes by #204, just replace the current value of customer list in JSON to null then set the value again using command or just delete all rental information and add back again.
