### ISSUE TITLE
Rental information customer list not rendering properly

### ISSUE THREAD

**Issue by zackjh** [AY2425S1-CS2103T-T15-1/tp#249]
E.g. After running the command `radd 1 a/BLK 1 Bishan s/01/01/2024 e/31/12/2024 dd/15 m/2700 d/8100 cl/Steven;David`

The UI shows this:
<img width="277" alt="Screenshot 2024-11-06 at 4 57 02 PM" src="https://github.com/user-attachments/assets/c358dc1a-2adc-4fb8-86a3-e66d8351fbfd">

The appropriate text that should be rendered is [Steven, David]

**Comment by gohsl99** [comment]
The original and correct behaviour is display as name;name;...
[name, name, ...] is not correct, the current behaviour has no issue.

**Comment by zackjh** [comment]
Ok, thanks for clarifying!
