### ISSUE TITLE
[PE-D][Tester A] Unlimited length phone number input allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-1/tp#297]
![image.png](https://raw.githubusercontent.com/Kitty-001/ped/main/files/bb3a7074-e0db-437e-9d74-e317f39db7cb.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Kitty-001/ped#1

**Comment by winstonlimjy** [comment]
This is as intended to give the user more flexibility.

Done. Updated in UG/DG.
