### ISSUE TITLE
[PE-D][Tester E] Misleading naming and usefulness of RENT_DUE_DATE in radd command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-1/tp#302]
![image.png](https://raw.githubusercontent.com/tzuennn/ped/main/files/c6df2ef1-bf46-4d28-a22d-dcceb73aab17.png)

Misleading naming, rent due date, I would expect a date not an integer between 1 to 31. While this field is thoughtful, is it really useful? After adding a rent due date, does the user need to manually update it each day? or will it automatically update.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: tzuennn/ped#6

**Comment by gohsl99** [comment]
Will use day instead, and include explanation in UG.

**Comment by gohsl99** [comment]
Potential fix in #370.
