### ISSUE TITLE
[PE-D][Tester B] [APP] Name parameter able to accepts numerical values

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-1/tp#308]
![image.png](https://raw.githubusercontent.com/PresleyChew/ped/main/files/0f79192d-fd65-4825-982a-9028d185c947.png)

Able to add via `cadd n/1234567890 p/99999999` , names should be alphabetical only and not be allowed to consist of numerical values.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: PresleyChew/ped#14

**Comment by winstonlimjy** [comment]
It is intended to give the user more flexibility in naming their clients.
