### ISSUE TITLE
[PE-D][Tester E] Find function returns wrong output and with duplicate entries

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-1/tp#315]
![Screenshot 2024-11-08 at 4.39.38 PM.png](https://raw.githubusercontent.com/tzuennn/ped/main/files/1ddab72f-8286-4b2e-acd5-b2fd19bce016.png)
I ran find n/____, which should be working, but this is ran after the find function stopped functioning as described in the previous issue.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tzuennn/ped#7

**Comment by winstonlimjy** [comment]
Fixed in PR #375
