### ISSUE TITLE
[PE-D][Tester E] Tab key not clear

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-1/tp#323]
![image.png](https://raw.githubusercontent.com/tzuennn/ped/main/files/d6a9e6a5-7be1-476b-8477-50bc1f3c86de.png)

![image.png](https://raw.githubusercontent.com/tzuennn/ped/main/files/2240e6a0-0fba-46f0-a03f-360dfc297868.png)

It is unclear how the autofills work.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: tzuennn/ped#8

**Comment by gohsl99** [comment]
Will list all the available command name, prefixes for command, and the helping words in UG.

**Comment by gohsl99** [comment]
Potential fix in #370.
