### ISSUE TITLE
[PE-D][Tester D] [DG]  Typo

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-1/tp#344]
Should be "or" not "and " as the Application works if either client or rental information is present

![Screenshot 2024-11-08 at 5.27.12 PM.png](https://raw.githubusercontent.com/travisim/ped/main/files/aa2cfa27-21ca-4194-afbd-2355d7398169.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: travisim/ped#10

**Comment by RobotWizzard** [comment]
I don't think this is a bug, the manual testing should test if **both** clients and rental information are cleared from the app.
