### ISSUE TITLE
[PE-D][Tester C] Wrong choice of parameter name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-1/tp#349]
![Screenshot 2024-11-08 at 5.33.57 PM.png](https://raw.githubusercontent.com/jevan13/ped/main/files/701186a6-3580-4d92-8ce7-91982b3cd3cb.png)
* If the parameter is meant to be a number from 1 to 31 it should not be called "Rent due date"
* Not very intuitive for users to think that rent due date is a number and not a date, when rent start date and rent end date are date formats
* Can use the word "Day" instead

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jevan13/ped#9

**Comment by gohsl99** [comment]
date may be ambiguous here, will use day and explain in UG.

**Comment by gohsl99** [comment]
Potential fix in #370.
