### ISSUE TITLE
[PE-D][Tester A] Unnecessary line in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-1/tp#351]
![image.png](https://raw.githubusercontent.com/Kitty-001/ped/main/files/07b00ff0-6390-4830-af4e-581160cb3fdc.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Kitty-001/ped#5

**Comment by winstonlimjy** [comment]
Done. Updated in UG/DG.
