### ISSUE TITLE
[PE-D][Tester C] Different error messages for same error

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-1/tp#352]
![Screenshot 2024-11-08 at 5.49.10 PM.png](https://raw.githubusercontent.com/jevan13/ped/main/files/833b04f9-cee8-4f3e-9882-cf2f76aa30f9.png)
![Screenshot 2024-11-08 at 5.49.22 PM.png](https://raw.githubusercontent.com/jevan13/ped/main/files/ad3b226d-498a-4a61-a45b-46962ffd5546.png)
* Both error caused by inputing a number large than the size of the list, but both returns different error messages

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jevan13/ped#10

**Comment by winstonlimjy** [comment]
Unfortunately, we regret to see this happening.

However, we are unable to change this error message as it does not prevent the user from using the application correctly. The v1.6 feature freeze does not allow us to edit this error message.

We will add this into the **known issue** under the user guide.

![image](https://github.com/user-attachments/assets/40609a5c-02b1-47c3-aba3-d6dffb9a9f1e)

**Comment by winstonlimjy** [comment]
The response was rejected due to it being a feature flaw. Customise error messages are not allowed in v1.6.
