### ISSUE TITLE
[PE-D][Tester A] No direct note for input format for dates for `redit`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-1/tp#356]
There is no more note on start date, end date, and due date format. Only to find out in the example or when typing in.

![image.png](https://raw.githubusercontent.com/Kitty-001/ped/main/files/2eb34352-9522-4795-9d8d-a7f49f39e3de.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Kitty-001/ped#8

**Comment by gohsl99** [comment]
More details should be found in parameter sections, will add it in the UG.

**Comment by gohsl99** [comment]
Potential fix in #370.
