### ISSUE TITLE
[PE-D][Tester C] Editing customer list requires retyping entire list again

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-1/tp#359]
![Screenshot 2024-11-08 at 6.23.38 PM.png](https://raw.githubusercontent.com/jevan13/ped/main/files/5c2c4c4e-26ef-4b7f-9c9b-a26f1f8350c4.png)

* Customer list is added as an entire string
* Changing a long customer list (example 20 customers) requires the user to retype the entire list, causing inconvenience
* A function could be made to edit certain customers, e.g. redit CLIENT_INDEX r/RENTAL_INDEX [cl/OLD CUSTOMER;NEW CUSTOMER]

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jevan13/ped#13

**Comment by gohsl99** [comment]
This is intended behaviour, will point this out in UG.

**Comment by gohsl99** [comment]
Potential fix in #370. Will include in future enhancement.
